name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.9', '3.10', '3.11', '3.12' ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Install Dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -e .

      - name: Test with unittest
        run: python -m unittest discover -s tests
        #continue-on-error: true
